### ISSUE TITLE
What's the state of Postgres implementation?

### ISSUE THREAD

**Issue by hickst** [Caltech-IPAC/nexsciTAP#11]
The docs say "We plan to implement PostgreSQL next....". What's the current state of this implementation? Has there been any progress on it?

**Comment by GBruceB** [comment]
Thank you for your ticket. At the moment we are implementing MySQL because  a major customer is using that DMBS. We will likely PostreSQL early in 2022.   

Sincerely

Bruce Berriman

**Comment by hickst** [comment]
Thanks for the update!
